name: 'Gcp Secrets'
description: 'Upsert a secret on GCLOUD if is changed'
inputs:
  secrets: # id of input
    description: 'The secrets list'
  project_id: # id of input
    description: 'the project identifier'
    required: false
runs:
  using: 'composite'
  steps:
    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
    - run: node ./dist/index.js
      shell: bash
      env:
        PROJECT_ID: ${{ inputs.project_id }}
        SECRETS: ${{ inputs.secrets }}
