name: 'Gcp Secrets'
description: 'Upsert a secret on GCLOUD if is changed'
inputs:
  secrets:
    description: 'The secrets list'
  project_id:
    description: 'the project identifier'
    required: false
runs:
  using: node20
  main: dist/index.js
