name: 'Gcp Secrets'
description: 'Upsert a secret on GCLOUD if is changed'
inputs:
  secret_name: # id of input
    description: 'The secret name'
    required: true
  secret_value: # id of input
    description: 'The secret value'
    required: true
  project_id: # id of input
    description: 'the project identifier'
    required: false
runs:
  using: 'composite'
  steps:
    - run: node ./dist/index.js
      shell: bash
      env:
        SECRET_NAME: ${{ github.secret_name }}
        SECRET_VALUE: ${{ inputs.secret_value }}
        PROJECT_ID: ${{ inputs.project_id }}
