on:
  workflow_call:
    inputs:
      GCP_PROJECT_ID:
        required: true
        type: string
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
        type: string
      GCP_SERVICE_ACCOUNT:
        required: true
        type: string
      SECRET_1:
        required: true
        type: string
      SECRET_2:
        required: true
        type: string

jobs:
  provision:
    name: 'Provision and deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate with GCP'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ inputs.GCP_PROJECT_ID }}

      - uses: nearform-actions/github-action-gcp-secret@v1
        with:
          secrets: |-
            secret1:"${{ inputs.SECRET_1 }}"
            secret2:"${{ inputs.SECRET_2 }}"

      - name: 'Show summary'
        run: >-
          echo "App successfully deployed."
