name: Continuous integration E2E

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  e2e:
    name: 'End 2 end test'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate with GCP'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: 'Remove the existent secrets'
        run: |
          npm ci
          node scripts/delete-secret.js github-action-gcp-secrets secret1
          node scripts/delete-secret.js github-action-gcp-secrets secret2

      - uses: ./
        with:
          secrets: |-
            secret1:"${{ vars.SECRET_1 }}"
            secret2:"${{ vars.SECRET_2 }}"

      - name: 'Check the secrets are created'
        run: |
          node scripts/verify-secret.js ${{ vars.GCP_PROJECT_ID }} secret1 1 "${{ vars.SECRET_1 }}"
          node scripts/verify-secret.js ${{ vars.GCP_PROJECT_ID }} secret2 1 "${{ vars.SECRET_2 }}"

      - uses: ./
        with:
          secrets: |-
            secret1:"${{ vars.SECRET_1 }}"
            secret2:"new-value"    

      - name: 'Check the secrets are created'
        run: |
          node scripts/verify-secret.js ${{ vars.GCP_PROJECT_ID }} secret1 1 "${{ vars.SECRET_1 }}"
          node scripts/verify-secret.js ${{ vars.GCP_PROJECT_ID }} secret2 2 "new-value"

      - name: 'Show summary'
        run: >-
          echo "End 2 end test success."
