name: Action test

on:
  push:
    branches:
      - main

jobs:
  action-tet:
    name: Custom github action test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          secret-name: 'projects/slack-kb-chatgpt-responder/secrets/test-action'
          secret-value: 'new-value'
